#!/bin/bash

# MCP Shell - Development Setup Script
# Copyright (C) 2025 Rafael
# Licensed under GPL-3.0
#
# This script sets up the development environment for MCP Shell.

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check Go installation
check_go() {
    if ! command_exists go; then
        error "Go is not installed. Please install Go 1.21 or later."
        error "Visit: https://golang.org/doc/install"
        return 1
    fi

    local go_version
    go_version=$(go version | grep -oE 'go[0-9]+\.[0-9]+' | sed 's/go//')
    local major
    major=$(echo "$go_version" | cut -d. -f1)
    local minor
    minor=$(echo "$go_version" | cut -d. -f2)

    if [[ "$major" -lt 1 ]] || [[ "$major" -eq 1 && "$minor" -lt 21 ]]; then
        error "Go version $go_version is too old. Please install Go 1.21 or later."
        return 1
    fi

    success "Go $go_version is installed"
}

# Check Git installation
check_git() {
    if ! command_exists git; then
        error "Git is not installed. Please install Git."
        return 1
    fi

    success "Git is installed"

    # Check if we're in a git repository
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        warning "Not in a git repository. Consider initializing git: git init"
    fi
}

# Setup Go modules
setup_go_modules() {
    info "Setting up Go modules..."

    cd "$PROJECT_ROOT"

    if [[ ! -f "go.mod" ]]; then
        error "go.mod not found. This should be automatically generated by cookiecutter."
        return 1
    fi

    # Download dependencies
    go mod download
    go mod tidy

    success "Go modules setup completed"
}

# Check and suggest optional tools
suggest_optional_tools() {
    info "Checking optional development tools..."

    local tools=(
        "golangci-lint:Linting:https://golangci-lint.run/usage/install/"
        "gosec:Security scanning:https://github.com/securecodewarrior/gosec#install"
        "govulncheck:Vulnerability checking:go install golang.org/x/vuln/cmd/govulncheck@latest"
        "task:Task runner:https://taskfile.dev/installation/"
        "hugo:Documentation:https://gohugo.io/installation/"
        "gh:GitHub CLI:https://cli.github.com/"
        "direnv:Environment management:https://direnv.net/docs/installation.html"
    )

    local missing_tools=()

    for tool_info in "${tools[@]}"; do
        IFS=':' read -r tool description install_info <<< "$tool_info"

        if command_exists "$tool"; then
            success "✓ $tool ($description) is installed"
        else
            warning "✗ $tool ($description) is not installed"
            missing_tools+=("$tool_info")
        fi
    done

    if [[ ${#missing_tools[@]} -gt 0 ]]; then
        echo
        info "Suggested installations for optimal development experience:"
        for tool_info in "${missing_tools[@]}"; do
            IFS=':' read -r tool description install_info <<< "$tool_info"
            echo "  • $tool ($description): $install_info"
        done
    fi
}

# Setup development environment
setup_dev_environment() {
    info "Setting up development environment..."

    # Create necessary directories
    mkdir -p "$PROJECT_ROOT/bin"
    mkdir -p "$PROJECT_ROOT/tmp"

    # Setup git hooks if git is available and we're in a git repo
    if command_exists git && git rev-parse --git-dir > /dev/null 2>&1; then
        setup_git_hooks
    fi

    success "Development environment setup completed"
}

# Setup git hooks
setup_git_hooks() {
    local hooks_dir="$PROJECT_ROOT/.git/hooks"

    if [[ ! -d "$hooks_dir" ]]; then
        warning "Git hooks directory not found, skipping git hooks setup"
        return
    fi

    info "Setting up git hooks..."

    # Pre-commit hook
    cat > "$hooks_dir/pre-commit" << 'EOF'
#!/bin/bash
# Pre-commit hook for MCP Shell

set -e

echo "Running pre-commit checks..."

# Format code
echo "• Formatting Go code..."
go fmt ./...

# Run linting if available
if command -v golangci-lint >/dev/null 2>&1; then
    echo "• Running golangci-lint..."
    golangci-lint run
elif command -v task >/dev/null 2>&1; then
    echo "• Running task lint..."
    task lint
else
    echo "• Running go vet..."
    go vet ./...
fi

# Run tests
echo "• Running tests..."
if command -v task >/dev/null 2>&1; then
    task test-unit
else
    go test -short ./...
fi

echo "Pre-commit checks passed!"
EOF

    chmod +x "$hooks_dir/pre-commit"
    success "Git pre-commit hook installed"
}

# Run initial build and test
run_initial_checks() {
    info "Running initial build and tests..."

    cd "$PROJECT_ROOT"

    # Build the project
    if command_exists task; then
        task build
    else
        go build -o bin/mcp-shell ./cmd/mcp-shell
    fi

    # Run tests
    if command_exists task; then
        task test-unit
    else
        go test ./...
    fi

    success "Initial build and tests completed successfully"
}

# Check Nix setup
check_nix_setup() {
    if command_exists nix; then
        info "Nix is available"

        if [[ -f "$PROJECT_ROOT/flake.nix" ]]; then
            info "Nix flake found. You can use 'nix develop' for a complete development environment."

            if command_exists direnv && [[ -f "$PROJECT_ROOT/.envrc" ]]; then
                info "direnv is available and .envrc exists. Run 'direnv allow' to auto-load the development environment."
            fi
        fi
    else
        info "Nix is not available. Consider installing Nix for a reproducible development environment."
        info "Visit: https://nixos.org/download.html"
    fi
}

# Display setup summary
show_setup_summary() {
    echo
    success "Development setup completed!"
    echo
    info "Quick start commands:"
    if command_exists task; then
        info "  task           # Show all available tasks"
        info "  task build     # Build the project"
        info "  task test      # Run all tests"
        info "  task lint      # Run linting"
        info "  task all       # Run complete pipeline"
    else
        info "  go build ./cmd/mcp-shell  # Build the project"
        info "  go test ./...                              # Run tests"
        info "  go run ./cmd/mcp-shell   # Run the application"
    fi
    echo
    info "Development workflow:"
    info "  1. Make your changes"
    info "  2. Run tests: task test (or go test ./...)"
    info "  3. Check linting: task lint (or golangci-lint run)"
    info "  4. Build: task build (or go build ./cmd/mcp-shell)"
    info "  5. Test the binary: ./bin/mcp-shell"
    echo
    info "Documentation:"
    info "  • README.md - Project overview and usage"
    info "  • ROADMAP.md - Development roadmap"
    if [[ -d "$PROJECT_ROOT/docs" ]]; then
        info "  • docs/ - Hugo documentation site"
        if command_exists hugo; then
            info "    Run 'hugo serve' in docs/ to preview locally"
        fi
    fi
    echo
    info "Need help? Check out the functions in functions.sh for development shortcuts!"
    if [[ -f "$PROJECT_ROOT/functions.sh" ]]; then
        info "  Source it with: source functions.sh"
        info "  Or run: dev-help"
    fi
    echo
}

# Show help
show_help() {
    cat << EOF
MCP Shell Development Setup Script

Usage: $0 [OPTIONS]

Options:
    -h, --help          Show this help message
    -q, --quick         Skip optional tool checks and suggestions
    --skip-build        Skip initial build and test
    --skip-hooks        Skip git hooks setup

This script will:
    • Verify Go and Git installations
    • Setup Go modules and dependencies
    • Check for optional development tools
    • Setup development environment
    • Configure git hooks (if in a git repository)
    • Run initial build and tests

Examples:
    $0                  # Full setup
    $0 --quick          # Quick setup without tool suggestions
    $0 --skip-build     # Setup without initial build

EOF
}

# Main function
main() {
    local quick=false
    local skip_build=false
    local skip_hooks=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_help
                exit 0
                ;;
            -q|--quick)
                quick=true
                shift
                ;;
            --skip-build)
                skip_build=true
                shift
                ;;
            --skip-hooks)
                skip_hooks=true
                shift
                ;;
            -*)
                error "Unknown option: $1"
                show_help
                exit 1
                ;;
            *)
                error "Unexpected argument: $1"
                show_help
                exit 1
                ;;
        esac
    done

    info "Starting development environment setup for MCP Shell"
    echo

    # Change to project root
    cd "$PROJECT_ROOT"

    # Check prerequisites
    check_go
    check_git

    # Setup Go modules
    setup_go_modules

    # Check optional tools
    if [[ "$quick" != true ]]; then
        suggest_optional_tools
        echo
    fi

    # Setup development environment
    setup_dev_environment

    # Check Nix setup
    check_nix_setup

    # Run initial checks
    if [[ "$skip_build" != true ]]; then
        echo
        run_initial_checks
    fi

    # Show summary
    show_setup_summary
}

# Handle script being sourced vs executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi